/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.tributacao.view;

import erp.tributacao.entidade.CondicaoTributo;
import erp.tributacao.entidade.NaturezaOperacao;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author leonardo
 */
public class CondicaoTributoView extends javax.swing.JPanel {
    
    private CondicaoTributo condicaoTributo;
    
    /**
     * Creates new form CondicaoTributoView
     */
    public CondicaoTributoView() {
        initComponents();
    }

    public CondicaoTributo getCondicaoTributo() {
        return condicaoTributo;
    }

    public JButton getButtonEditarCondicao() {
        return buttonEditarCondicao;
    }

    public JButton getButtonEditarScript() {
        return buttonEditarScript;
    }

    public JLabel getLabel() {
        return label;
    }

    public CondicaoTributoView(CondicaoTributo condicaoTributo) {
        this();
        this.condicaoTributo = condicaoTributo;
        if (condicaoTributo instanceof NaturezaOperacao) {
            this.label.setText(((NaturezaOperacao) condicaoTributo).getDescricao());
            setBackground(Color.ORANGE);
        }
        else {
            this.label.setText(condicaoTributo.getScriptCondicaoTributo().getDescricao());
        }
        setBounds(condicaoTributo.getBounds());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        buttonEditarCondicao = new javax.swing.JButton();
        buttonEditarScript = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        label.setText("Descricao da condicao");
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMousePressed(evt);
            }
        });
        label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelMouseDragged(evt);
            }
        });

        buttonEditarCondicao.setText("c");
        buttonEditarCondicao.setBorder(null);

        buttonEditarScript.setText("s");
        buttonEditarScript.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(buttonEditarCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditarScript, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(buttonEditarScript)
                .addComponent(buttonEditarCondicao))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
        condicaoTributo.setBounds(getBounds());
        
        Panel parentPanel = (Panel) getParent();
        parentPanel.reajustarTamanhoMaximo();
        parentPanel.repaint();
        parentPanel.updateUI();
    }//GEN-LAST:event_labelMouseDragged

    int x = 0;
    int y = 0;
    private void labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMousePressed
        x = evt.getXOnScreen() - getLocation().x;
        y = evt.getYOnScreen() - getLocation().y;
    }//GEN-LAST:event_labelMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditarCondicao;
    private javax.swing.JButton buttonEditarScript;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
