package erp.tributacao.view;

import erp.tributacao.core.FluxoTributacao;
import erp.tributacao.core.LogicaTributacao;
import erp.tributacao.core.LogicaTributacao.Tipo;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author leonardo
 */
public class EdicaoCondicaoView extends javax.swing.JFrame {

    private FluxoTributacao condicaoTributo;
    
    /**
     * Creates new form EdicaoCondicaoView
     */
    public EdicaoCondicaoView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public FluxoTributacao getCondicaoTributo() {
        return condicaoTributo;
    }

    public void setCondicaoTributo(FluxoTributacao condicaoTributo) {
        this.condicaoTributo = condicaoTributo;
        if (condicaoTributo.getScriptCondicaoTributo() == null) return;
        txtDescricao.setText(condicaoTributo.getScriptCondicaoTributo().getDescricao());
        txtScript.setText(condicaoTributo.getScriptCondicaoTributo().getScript());
        if (condicaoTributo.getScriptCondicaoTributo().getTipo() == Tipo.CONDICAO) {
            radioCondicao.setSelected(true);
        }
        else {
            radioAplicacao.setSelected(true);
        }
    }

    public JButton getButtonAdicionar() {
        return buttonAdicionar;
    }

    public JButton getButtonAlterar() {
        return buttonAlterar;
    }

    public JButton getButtonCancelar() {
        return buttonCancelar;
    }

    public JTextField getTxtDescricao() {
        return txtDescricao;
    }

    public JTextArea getTxtScript() {
        return txtScript;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtScript = new javax.swing.JTextArea();
        buttonAdicionar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        radioCondicao = new javax.swing.JRadioButton();
        radioAplicacao = new javax.swing.JRadioButton();
        buttonAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Descricao:");

        jLabel3.setText("Script:");

        txtScript.setColumns(20);
        txtScript.setRows(5);
        jScrollPane2.setViewportView(txtScript);

        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonGroup.add(radioCondicao);
        radioCondicao.setText("Condicao");

        buttonGroup.add(radioAplicacao);
        radioAplicacao.setSelected(true);
        radioAplicacao.setText("Aplicacao");

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(buttonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioCondicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioAplicacao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDescricao))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCondicao)
                    .addComponent(radioAplicacao)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonAdicionar)
                        .addComponent(buttonAlterar))
                    .addComponent(buttonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        CondicaoTributoView ctView = (CondicaoTributoView) condicaoTributo.getViewComponent();
        Tipo tipo = Tipo.CONDICAO;
        if (radioAplicacao.isSelected()) {
            tipo = Tipo.APLICACAO;
        }
        LogicaTributacao script = new LogicaTributacao(txtDescricao.getText(), txtScript.getText(), tipo);
        FluxoTributacao novaCondicao = new FluxoTributacao(condicaoTributo.getContexto(), script);
        novaCondicao.setBounds(ctView.getX() + ctView.getWidth() + 20, ctView.getY() + ctView.getHeight(), ctView.getWidth(), ctView.getHeight());
        condicaoTributo.getProximasCondicoes().add(novaCondicao);
        Container parent = ctView.getParent();
        while (!(parent instanceof View)) {
            parent = parent.getParent();
        }
        View view = (View) parent;
        view.addCondicaoTributo(novaCondicao);
        setVisible(false);
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        LogicaTributacao script = condicaoTributo.getScriptCondicaoTributo();
        script.setDescricao(txtDescricao.getText());
        script.setScript(txtScript.getText());
        if (radioCondicao.isSelected()) {
            script.setTipo(Tipo.CONDICAO);
        }
        else {
            script.setTipo(Tipo.APLICACAO);
        }
        setVisible(false);
    }//GEN-LAST:event_buttonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicaoCondicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicaoCondicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicaoCondicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicaoCondicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicaoCondicaoView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioAplicacao;
    private javax.swing.JRadioButton radioCondicao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextArea txtScript;
    // End of variables declaration//GEN-END:variables
}
