/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.tributacao.view;

import erp.tributacao.entidade.CondicaoTributo;
import erp.tributacao.entidade.NaturezaOperacao;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.geom.Line2D;

/**
 *
 * @author leonardo
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    @Override
    public Component add(Component comp) {
        Component c = super.add(comp);
        reajustarTamanhoMaximo();
        return c;
    }

    public void reajustarTamanhoMaximo() {
        int widthMax = 0;
        int heightMax = 0;
        for (Component c : getComponents()) {
            int w = c.getX() + c.getWidth();
            int h = c.getY() + c.getHeight();
            if (w > widthMax) widthMax = w;
            if (h > heightMax) heightMax = h;
        }
        widthMax += 50;
        heightMax += 50;
        setPreferredSize(new Dimension(widthMax, heightMax));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 102));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Ao clicar na linha que associa a condicao pai ao filho,
    // essa associacao e removida. Porem os objetos em si ainda permanecem.
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        fora:
        for (Component c : getComponents()) {
            CondicaoTributoView ctv = (CondicaoTributoView) c;
            int xini = ctv.getX() + ctv.getWidth();
            int yini = ctv.getY() + (ctv.getHeight()/2);
            CondicaoTributo ct = ctv.getCondicaoTributo();
            for (CondicaoTributo ctl : ct.getProximasCondicoes()) {
                int xfin = ctl.getBounds().x;
                int yfin = ctl.getBounds().y + (ctl.getBounds().height/2);
                Line2D.Float line = new Line2D.Float(xini, yini, xfin, yfin);
                boolean contains = (line.ptLineDist(x, y) < 2);
                if (contains) {
                    System.out.println("Removendo: " + contains);
                    ct.getProximasCondicoes().remove(ctl);
                    return;
                }
            }
        }
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.GRAY);
        for (int x=0; x<=getWidth(); x+=10) {
            for (int y=0; y<=getHeight(); y+=10) {
                g.drawLine(x, y, x, y);
            }
        }
        g.setColor(Color.WHITE);
        for (Component c : getComponents()) {
            CondicaoTributoView ctv = (CondicaoTributoView) c;
            int xini = ctv.getX() + ctv.getWidth();
            int yini = ctv.getY() + (ctv.getHeight()/2);
            CondicaoTributo ct = ctv.getCondicaoTributo();
            for (CondicaoTributo ctl : ct.getProximasCondicoes()) {
                int xfin = ctl.getBounds().x;
                int yfin = ctl.getBounds().y + (ctl.getBounds().height/2);
                g.drawLine(xini, yini-1, xfin, yfin-1);
                g.drawLine(xini, yini+0, xfin, yfin+0);
                g.drawLine(xini, yini+1, xfin, yfin+1);
            }
            if (ct instanceof NaturezaOperacao) {
                setFont(new Font("arial", Font.PLAIN, 9));
                g.drawString("Natureza de Operação:", ct.getBounds().x, ct.getBounds().y - 2);
            }
        }
    }
    
}
