package erp.infra.test;

import erp.infra.Form;
import erp.infra.FormController;
import erp.infra.GridController;
import java.util.ArrayList;
import java.util.List;

/**
 * View class.
 *
 * @author Leonardo Ono (ono.leo@gmail.com)
 * @since 1.00.00 (28/01/2013 00:06)
 */
public class View extends javax.swing.JFrame {

    private FormController<Pais> formController = new FormController<Pais>() {
        
        private Pais entity;
        
        @Override
        public Pais getEntity() {
            return entity;
        }

        @Override
        public void setEntity(Pais entity) {
            this.entity = entity;
        }
        
        @Override
        public void reload() throws Exception {
            /*
            Pais pais = new Pais();
            pais.setId(1L);
            pais.setCodigoBacen("1058");
            pais.setNome("BRASIL");
            pais.setSigla2("BR");
            entity = pais;
            */
        }

        @Override
        public void update() throws Exception {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void insert() throws Exception {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void delete() throws Exception {
            throw new UnsupportedOperationException("Not supported yet.");
        }



    };
    private GridController<Pais> gridController = new GridController<Pais>() {
        @Override
        public List<Pais> reload() throws Exception {
            List<Pais> list = new ArrayList<Pais>();
            for (int i = 0; i < 30; i++) {
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
                list.add(new Pais(1L, "1058", "BRASIL", "BR"));
                list.add(new Pais(2L, "1034", "ESTADOS UNIDOS", "EU"));
                list.add(new Pais(3L, "1098", "JAPAO", "JP"));
            }
            return list;
        }

        @Override
        public void update(List<Pais> t) throws Exception {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void insert(List<Pais> t) throws Exception {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void delete(List<Pais> t) throws Exception {
            throw new UnsupportedOperationException("Not supported yet.");
        }
    };

    public View() {
        initComponents();
        form.setController(formController);
        grid.setController(gridController);
        grid.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new erp.infra.Form();
        field1 = new erp.infra.Field();
        field2 = new erp.infra.Field();
        field3 = new erp.infra.Field();
        field4 = new erp.infra.Field();
        buttonAtualizarGrid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid = new erp.infra.Grid();
        field5 = new erp.infra.Field();
        buttonAtualizar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        field1.setEditableOnInsert(false);
        field1.setEditableOnUpdate(false);
        field1.setLabelText("Id");
        field1.setProperty("id");

        field2.setLabelText("Cód. BACEN");
        field2.setProperty("codigoBacen");
        field2.setRequired(true);

        field3.setLabelText("Nome");
        field3.setProperty("nome");
        field3.setRequired(true);

        field4.setLabelText("Sigla 2");
        field4.setProperty("sigla2");
        field4.setRequired(true);

        buttonAtualizarGrid.setText("Atualizar");
        buttonAtualizarGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarGridActionPerformed(evt);
            }
        });

        grid.setFormModel(form);
        jScrollPane1.setViewportView(grid);

        field5.setExpression("entity.id + ' - ' + entity.codigoBacen + ' - ' + entity.nome + ' - ' + entity.sigla2");
        field5.setLabelText("Campo");
        field5.setRequired(true);

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formLayout.createSequentialGroup()
                                .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(field5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(formLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAtualizarGrid)))
                .addContainerGap())
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(buttonAtualizarGrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonAtualizar.setText("Atualizar");
        buttonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarActionPerformed(evt);
            }
        });

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(buttonAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAtualizar)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonEditar)
                    .addComponent(buttonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarActionPerformed
        form.reload();
    }//GEN-LAST:event_buttonAtualizarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        form.insert();
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonAtualizarGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarGridActionPerformed
        grid.reload();
    }//GEN-LAST:event_buttonAtualizarGridActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        form.setMode(Form.Mode.UPDATE);
        grid.setEnabled(false);
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        form.setMode(Form.Mode.READ_ONLY);
        form.reload();
        grid.setEnabled(true);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonAtualizarGrid;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonSalvar;
    private erp.infra.Field field1;
    private erp.infra.Field field2;
    private erp.infra.Field field3;
    private erp.infra.Field field4;
    private erp.infra.Field field5;
    private erp.infra.Form form;
    private erp.infra.Grid grid;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
