package erp.infra;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Field class.
 * 
 * @author Leonardo Ono (ono.leo@gmail.com)
 * @since 1.00.00 (27/01/2013 21:12)
 */
public class Field extends JPanel {

    private String property;
    
    /**
     * Creates new form Field
     */
    public Field() {
        initComponents();
    }

    public String getProperty() {
        return property;
    }

    public void setProperty(String property) {
        this.property = property;
    }

    public void setLabelText(String labelText) {
        this.label.setText(labelText);
    }
    
    public String getLabelText() {
        return label.getText();
    }

    public void setFieldText(String fieldText) {
        this.text.setText(fieldText);
    }
    
    public String getFieldText() {
        return text.getText();
    }

    public JLabel getLabel() {
        return label;
    }

    public void setLabel(JLabel label) {
        this.label = label;
    }

    public JLabel getLabelMessage() {
        return labelMessage;
    }

    public void setLabelMessage(JLabel labelMessage) {
        this.labelMessage = labelMessage;
    }

    public JTextField getText() {
        return text;
    }

    public void setText(JTextField text) {
        this.text = text;
    }
    
    @Override
    public void setEnabled(boolean enabled) {
        text.setEnabled(enabled);
    }
    
    @Override
    public boolean isEnabled() {
        return text.isEnabled();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        labelMessage = new javax.swing.JLabel();
        text = new javax.swing.JTextField();

        label.setText("jLabel2");

        labelMessage.setText("jLabel1");

        setMinimumSize(new java.awt.Dimension(110, 30));
        setPreferredSize(new Dimension(150, text.getPreferredSize().height));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(text);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
