package erp.infra.button;

import javax.swing.JToolBar;

/**
 * CrudToolBar class.
 *
 * @author Leonardo Ono (ono.leo@gmail.com)
 * @since 1.00.00 (07/02/2013 09:40)
 */
public class CrudToolBar extends JToolBar {

    /**
     * Creates new form CrudToolBar
     */
    public CrudToolBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reloadButton1 = new erp.infra.button.ReloadCrudButton();
        insertButton1 = new erp.infra.button.InsertButton();
        updateButton1 = new erp.infra.button.UpdateButton();
        deleteButton1 = new erp.infra.button.DeleteButton();
        saveButton2 = new erp.infra.button.SaveButton();
        cancelButton2 = new erp.infra.button.CancelButton();

        reloadButton1.setText("reloadButton1");
        reloadButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reloadButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(reloadButton1);

        insertButton1.setText("insertButton1");
        insertButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(insertButton1);

        updateButton1.setText("updateButton1");
        updateButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(updateButton1);

        deleteButton1.setText("deleteButton1");
        deleteButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(deleteButton1);

        saveButton2.setText("saveButton2");
        saveButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(saveButton2);

        cancelButton2.setText("cancelButton2");
        cancelButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(cancelButton2);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private erp.infra.button.CancelButton cancelButton2;
    private erp.infra.button.DeleteButton deleteButton1;
    private erp.infra.button.InsertButton insertButton1;
    private erp.infra.button.ReloadCrudButton reloadButton1;
    private erp.infra.button.SaveButton saveButton2;
    private erp.infra.button.UpdateButton updateButton1;
    // End of variables declaration//GEN-END:variables
}
