package erp.infra.button;

import erp.infra.form.FormModel;
import erp.infra.mode.ModeListener;
import javax.swing.JButton;

/**
 * GenericButton class.
 *
 * @author Leonardo Ono (ono.leo@gmail.com)
 * @since 1.00.00 (06/02/2013 12:59)
 */
public class GenericButton extends JButton implements ModeListener {
    
    protected FormModel formModel;
    
    public GenericButton() {
        initComponents();
    }

    public FormModel getFormModel() {
        return formModel;
    }

    public void setFormModel(FormModel formModel) {
        this.formModel = formModel;
        formModel.getModeModel().addListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(32, 32));
        setMinimumSize(new java.awt.Dimension(32, 32));
        setPreferredSize(new java.awt.Dimension(32, 32));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void setText(String text) {
    }

    @Override
    public void modeChanged() {
    }
    
}
