package erp.infra.button;

import br.beanlinker.core.BeanLinker;
import br.beanlinker.core.BeanLinkerImpl;
import erp.infra.form.FormModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 * Button class.
 * 
 * @author Leonardo Ono (ono.leo@gmail.com)
 * @since 1.00.00 (30/01/2013 14:55)
 */
public class Button extends JButton {
    
    private static BeanLinker linker = new BeanLinkerImpl();
    
    public enum Type { 
        RELOAD("model.reload()"), 
        INSERT("model.insert()"), 
        UPDATE("model.update()"), 
        DELETE("model.delete()"), 
        CANCEL("model.cancel()"), 
        FIRST("model.first()"), 
        PREVIOUS("model.previous()"), 
        NEXT("model.next()"),  
        LAST("model.last()");
        private String expression;
        private Type(String expression) {
            this.expression = expression;
        }
        public String getExpression() {
            return expression;
        }
    }
    
    private Type type = Type.RELOAD;
    private FormModel entityModel;
    
    public Button() {
        initComponents();
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public FormModel getEntityModel() {
        return entityModel;
    }

    public void setEntityModel(FormModel entityModel) {
        this.entityModel = entityModel;
        try {
            linker.assign("model", entityModel);
        } catch (Exception ex) {
            Logger.getLogger(Button.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(24, 24));
        addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formActionPerformed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formActionPerformed
        System.out.println(evt);
        if (entityModel == null) {
            return;
        }
        try {
            linker.eval(type.getExpression());
        } catch (Exception ex) {
            Logger.getLogger(Button.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
