package erp.infra.button;

import br.beanlinker.core.BeanLinker;
import br.beanlinker.core.BeanLinkerImpl;
import erp.infra.form.Form.Mode;
import erp.infra.form.FormModelListener;
import erp.infra.form.WrapperFormModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 * Button class.
 * 
 * @author Leonardo Ono (ono.leo@gmail.com)
 * @since 1.00.00 (30/01/2013 14:55)
 */
public class Button extends JButton implements FormModelListener {
    
    private static BeanLinker linker = new BeanLinkerImpl();
  
    public enum Type { 
        RELOAD("model.reload()"), 
        INSERT("model.insert()"), 
        UPDATE("model.update()"), 
        DELETE("model.delete()"), 
        CANCEL("model.cancel()"), 
        FIRST("model.first()"), 
        PREVIOUS("model.previous()"), 
        NEXT("model.next()"),  
        LAST("model.last()");
        private String expression;
        private Type(String expression) {
            this.expression = expression;
        }
        public String getExpression() {
            return expression;
        }
    }
    
    private Type type = Type.RELOAD;
    private WrapperFormModel entityModel;
    
    public Button() {
        initComponents();
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public WrapperFormModel getEntityModel() {
        return entityModel;
    }

    public void setEntityModel(WrapperFormModel entityModel) {
        this.entityModel = entityModel;
        entityModel.addListener(this);
        try {
            linker.assign("model", entityModel);
        } catch (Exception ex) {
            Logger.getLogger(Button.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(24, 24));
        addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formActionPerformed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formActionPerformed
        System.out.println("entityModel: " + entityModel + " evt: " + evt);
        if (entityModel == null) {
            return;
        }
        try {
            linker.eval(type.getExpression());
        } catch (Exception ex) {
            Logger.getLogger(Button.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    // --- FormModelListener implementation ---
    
    @Override
    public void modeChanged() {
        if (entityModel == null || type == null) {
            return;
        }
        
        if (entityModel.getMode() == Mode.EMPTY) {
            if (type == Type.CANCEL) {
                setEnabled(false);
            }
            else if (type == Type.DELETE) {
                setEnabled(false);
            }
            else if (type == Type.FIRST) {
                setEnabled(true);
            }
            else if (type == Type.INSERT) {
                setEnabled(true);
            }
            else if (type == Type.LAST) {
                setEnabled(true);
            }
            else if (type == Type.NEXT) {
                setEnabled(true);
            }
            else if (type == Type.PREVIOUS) {
                setEnabled(true);
            }
            else if (type == Type.RELOAD) {
                setEnabled(false);
            }
            else if (type == Type.UPDATE) {
                setEnabled(false);
            }
        }
        else if (entityModel.getMode() == Mode.READ_ONLY) {
            if (type == Type.CANCEL) {
                setEnabled(false);
            }
            else if (type == Type.DELETE) {
                setEnabled(true);
            }
            else if (type == Type.FIRST) {
                setEnabled(true);
            }
            else if (type == Type.INSERT) {
                setEnabled(true);
            }
            else if (type == Type.LAST) {
                setEnabled(true);
            }
            else if (type == Type.NEXT) {
                setEnabled(true);
            }
            else if (type == Type.PREVIOUS) {
                setEnabled(true);
            }
            else if (type == Type.RELOAD) {
                setEnabled(true);
            }
            else if (type == Type.UPDATE) {
                setEnabled(true);
            }
        }
        else if (entityModel.getMode() == Mode.INSERT) {
            if (type == Type.CANCEL) {
                setEnabled(true);
            }
            else if (type == Type.DELETE) {
                setEnabled(false);
            }
            else if (type == Type.FIRST) {
                setEnabled(false);
            }
            else if (type == Type.INSERT) {
                setEnabled(true);
            }
            else if (type == Type.LAST) {
                setEnabled(false);
            }
            else if (type == Type.NEXT) {
                setEnabled(false);
            }
            else if (type == Type.PREVIOUS) {
                setEnabled(false);
            }
            else if (type == Type.RELOAD) {
                setEnabled(false);
            }
            else if (type == Type.UPDATE) {
                setEnabled(false);
            }
        }
        else if (entityModel.getMode() == Mode.UPDATE) {
            if (type == Type.CANCEL) {
                setEnabled(true);
            }
            else if (type == Type.DELETE) {
                setEnabled(false);
            }
            else if (type == Type.FIRST) {
                setEnabled(false);
            }
            else if (type == Type.INSERT) {
                setEnabled(false);
            }
            else if (type == Type.LAST) {
                setEnabled(false);
            }
            else if (type == Type.NEXT) {
                setEnabled(false);
            }
            else if (type == Type.PREVIOUS) {
                setEnabled(false);
            }
            else if (type == Type.RELOAD) {
                setEnabled(true);
            }
            else if (type == Type.UPDATE) {
                setEnabled(true);
            }
        }
    }

    @Override
    public void entityChanged() {
    }

    @Override
    public void reloaded() {
    }

    @Override
    public void updated() {
    }

    @Override
    public void inserted() {
    }

    @Override
    public void canceled() {
    }

    @Override
    public void deleted() {
    }
    
}
